tests(azure-storage-service): fix test
nestjs/azure-storage pull request #148
Opened 2021-01-07 16:25 UTC by Tony133

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
This PR, fix test error "should fail upload when File is null"

2021-01-07 16:27 UTC, Tony133 commented
to be evaluated :-)

2021-01-08 14:18 UTC, manekinekko commented
Thank you for this contribution 👍

2021-01-08 14:34 UTC, manekinekko commented
@Tony133  Could you provide more feedback about the reason for this change?

2021-01-08 14:44 UTC, Tony133 commented
Hi @manekinekko, I made this change because I had made another pull this https://github.com/nestjs/azure-storage/pull/144

gave this error in tests: 

```PASS  lib/azure-nest-storage.module.spec.ts
 FAIL  lib/azure-storage.service.spec.ts
  ● AzureStorageService › should fail upload when File is null

    expect(received).toBe(expected) // Object.is equality

    Expected: "TypeError: Cannot destructure property `buffer` of 'undefined' or 'null'."
    Received: "TypeError: Cannot destructure property 'buffer' of 'file' as it is null."

      123 |       await storage.upload(null);
      124 |     } catch (e) {
    > 125 |       expect(e.toString()).toBe(
          |                            ^
      126 |         "TypeError: Cannot destructure property `buffer` of 'undefined' or 'null'.",
      127 |       );
      128 |     }
```

which has nothing to do with what I had done, so I tried to see if I could solve it.

The solution at the moment looks like this I hope it will go well.

2021-01-08 15:58 UTC, manekinekko requested changes

2021-01-08 15:58 UTC, manekinekko commented on lib/azure-storage.service.spec.ts
> +      await storage.upload(file, null);
```suggestion
      await storage.upload(null);
```

2021-01-08 15:58 UTC, manekinekko commented on lib/azure-storage.service.spec.ts
>          "TypeError: Cannot destructure property `buffer` of 'undefined' or 'null'.",
```suggestion
        "TypeError: Cannot destructure property 'buffer' of 'file' as it is null."
```

2021-01-08 15:59 UTC, manekinekko commented
Oh! I see what was the error.

It seems that the error message of the exception that is thrown when a file is `null`, has changed:

from:
```
TypeError: Cannot destructure property `buffer` of 'undefined' or 'null'.
```

To:
```
TypeError: Cannot destructure property 'buffer' of 'file' as it is null.
```

I've sent you few changes to make before merging the PR.

2021-01-08 16:04 UTC, Tony133 commented on lib/azure-storage.service.spec.ts
> +      await storage.upload(file, null);
So does this part come back as before?

2021-06-16 12:47 UTC, jasonpaige commented
Any chance this can get merged so that the build can be fixed please :pray: ? I'm keen to make use of the feature added with https://github.com/nestjs/azure-storage/pull/65 but the build has been broken since it was merged in last year :(

2021-06-18 09:48 UTC, merged